[package]
name = "GBEmulator"
version = "0.1.0"
authors = ["Ashiu <clement.milisavljevic@epita.fr>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
minifb = "0.23.0"
derive_more = "0.99.16"